# Generated by Django 5.2.8 on 2025-11-22 04:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_sampleauditlog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sampleauditlog",
            name="sample",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="audit_logs",
                to="core.sample",
            ),
        ),
    ]
